Welcome Message and guildMemberAdd test command
sfsu-acm/Lovelace pull request #11
Opened 2023-07-28 21:11 UTC by OskoPoland

Add slash command to test the guild member add command as well as a listener for the guild member add to auto create tagged welcome messages.

2023-07-28 21:18 UTC, leavism requested changes
Great work! Look at my reviews and make changes where it's needed.

2023-07-28 21:18 UTC, leavism commented on package.json
Any idea why you had to install this version node.js?

2023-07-28 21:18 UTC, leavism commented on src/commands/Bot/emitTest.ts
Nice work getting the emitter to work! We won't need this in the actual merge though. Remove it from the PR (pull request)

2023-07-28 21:18 UTC, leavism commented on src/listeners/guildMemberAddGreeting.ts
Rather than pointing to the #greet channel via a hard-coded channel ID, take a look at this:
https://old.discordjs.dev/#/docs/discord.js/main/class/Guild?scrollTo=systemChannel

A `systemChannel` is basically the channel in which the server sends the default vanilla welcome messages.

2023-07-28 21:23 UTC, OskoPoland commented on package.json
I actually have no idea. I will try and remove it and see if that breaks anything.

2023-07-28 21:23 UTC, OskoPoland commented on src/commands/Bot/emitTest.ts
Will do

2023-07-28 21:45 UTC, OskoPoland commented
I made the changes. The node security package I deleted and it didn't impeded anything so I have no clue. The greet channel message location is no longer hardcoded either instead using the systemChannelID to send the message to the correct channel.

I think the changes show up here I am not sure if I need to make a whole new pull request or if this works as well?

2023-07-28 21:52 UTC, leavism commented
> I made the changes. The node security package I deleted and it didn't impeded anything so I have no clue. The greet channel message location is no longer hardcoded either instead using the systemChannelID to send the message to the correct channel.
> 
> 
> 
> I think the changes show up here I am not sure if I need to make a whole new pull request or if this works as well?

Commit the new changes to your fork. The PR should automatically show the new commit. Hopefully hahaha

2023-07-28 23:37 UTC, leavism requested changes
I made direct commits to your fork, remember to `git pull` before you begin working on your local fork again. Take a look at what I said about your changes to `GuildMemberAddGreeting` and see if you can refactor your code to be even simpler.

2023-07-28 23:37 UTC, leavism commented on .gitignore
Ideally you'd just remove the file from your repo entirely because it's still uploaded to your remote repository. No worries if all of this is new and confusing, we are supposed to go over it in our next meeting.

2023-07-28 23:37 UTC, leavism commented on src/listeners/guildMemberAddGreeting.ts
You almost got it with this recent change. Look at the return type of `guild.systemChannel` provided in the link above. You don't need the `systemChannelID` if you already have a property that gives you the actual `systemChannel` object.

2023-07-29 06:25 UTC, OskoPoland commented
Ah I see I didn't look hard enough past the ID but I see that it has a TextChannel obj so I simplified the code some more so it's all a one-liner. I also added a listener and message for the removal as well since its practically the same thing.

2023-08-01 18:58 UTC, leavism reviewed
Nice work

2023-08-01 18:58 UTC, leavism commented on src/listeners/guildMemberAddGreeting.ts
Hey, you're still hard coding a guild ID. Try getting the guild from the GuildMember object that's passed into the run method.

2023-08-01 18:58 UTC, leavism commented on src/listeners/guildMemberAddGreeting.ts
This is the one. Nice work!

2023-08-01 19:41 UTC, leavism commented
Remove the `TextChannel` import from `discord.js` and we're good to merge.

2023-08-01 19:47 UTC, leavism approved these changes
LGTM

2023-08-01 19:48 UTC, merged