create Lovelace class extending SapphireClient with custom constructor, login, and destroy methods
sfsu-acm/Lovelace pull request #18
Opened 2024-11-19 22:19 UTC by Ca3dyn

#17 pull request for this issue

2024-11-19 22:24 UTC, leavism commented on src/index.ts
Thanks for separating the options out, makes it more legible.

2024-11-19 22:28 UTC, leavism requested changes
Add JSDocs, get ESLint and prettier working, and you should be good to go.

2024-11-19 22:28 UTC, leavism commented on src/lib/LovelaceClient.ts
Please add JSDocs to this class. It should be pretty barebones but at least get it started.
https://jsdoc.app/about-getting-started

2024-11-19 23:07 UTC, Ca3dyn commented
#18 pull request for JSDocs

2024-11-20 00:20 UTC, leavism reviewed
@Ca3dyn you probably want to get out of the habit of doing `git add .` or `git add -A` because you'll accidentally add files you didn't mean to, like you did this time.

2024-11-20 00:20 UTC, leavism commented on .vscode/settings.json
Please double check what you're committing before you push them.

2024-11-20 00:20 UTC, leavism commented on src/lib/LovelaceClient.ts
New JSDocs are good enough. I'm going to change some verbiage before I merge ("logs the _user_ into Discord" when it should be bot).

2024-11-20 00:52 UTC, leavism approved these changes
Made final changes, ready to merge!

2024-11-20 00:56 UTC, merged